# PENJELASAN
# - membuat sebuah Headless Service bernama 'mongodb'
# - menggunakan port default untuk mongodb, yaitu 27017

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    type: db
  clusterIP: None
