# PENJELASAN
# - Membuat Secret dengan nama mongodb-secret
# - berisi data MONGO_ROOT_USERNAME dan MONGO_ROOT_PASSWORD

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
stringData:
  MONGO_ROOT_USERNAME: admin
data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZAo=
